UPDATE players
SET hourly_last_at = DATE_ADD(hourly_last_at, INTERVAL 20 MINUTE)
WHERE hourly_last_at IS NOT NULL;

-- Création de la table economy_hourly si inexistante
CREATE TABLE IF NOT EXISTS economy_hourly (
    bucket_start DATETIME NOT NULL,
    player_id    BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (bucket_start, player_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Ajout individuel de chaque colonne si elle n'existe pas déjà
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS new_players         BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS returning_players   BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS claims              BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS full_claims         BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS mining_rtm          DECIMAL(38,5)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS event_hash_usd      DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS event_pin_usd       DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS event_decode_usd    DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS event_anomaly_usd   DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS event_buffer_usd    DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS event_signal_usd    DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS event_packet_usd    DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS grant_usd           DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS miners_usd          DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS miners_rtm          DECIMAL(38,5)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS combat_usd          DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS combat_rtm          DECIMAL(38,5)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS upgrades_usd        DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS hourly_claims       BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS hourly_usd          DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS contracts_collected BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS contracts_usd       DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS compile_rtm         DECIMAL(38,5)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS scan_rtm            DECIMAL(38,5)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS miners_t1           BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS miners_t2           BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS miners_t3           BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS miners_t4           BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS miners_t5           BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS attack_bought       BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS defense_bought      BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS upgrades_started    BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS conversions         BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS converted_rtm       DECIMAL(38,5)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS converted_usd       DECIMAL(38,2)   NOT NULL DEFAULT 0;
ALTER TABLE economy_hourly ADD COLUMN IF NOT EXISTS trades              BIGINT UNSIGNED NOT NULL DEFAULT 0;



